# -*- coding: utf-8 -*-
"""
Draw three compact waveform icons for insertion into a paper table.

Figure 1 (forward):
    actual input waveform (red)  ->  SSFM output waveform (blue)

Figure 2 (inverse, A_min = 0.05):
    predicted input waveform (blue)  <-  observed output waveform (red)
    The displayed input vector is manually constructed so that one tiny
    sub-pulse of amplitude 0.05 is placed near the center and its two
    neighboring pulses are intentionally larger, to visually emphasize
    the difficulty of recovering a very small pulse.

Figure 3 (inverse, A_min = 0.20):
    same as Figure 2, but the central small pulse is 0.20.

Notes
-----
- All "observed output waveforms" are generated by the project's real SSFM.
- For Figures 2 and 3, the displayed predicted-input waveform is intentionally
  constructed for illustration (rather than selected from the 200-sample pool),
  because the main goal is to visually explain the effect of A_min.
- Publication style matches the first universal-model K=8 waterfall figure:
      BLUE = #0000FF, lw = 1.10, alpha = 0.88
      RED  = #FF0000, lw = 0.95, alpha = 0.88
- Font: Times New Roman, 14 pt.
"""

from __future__ import annotations

import argparse
import csv
import importlib.util
import json
import sys
import warnings
from pathlib import Path
from typing import Any, Sequence

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import torch

from train_multi_pulse_pinn import NLSEParams

warnings.filterwarnings("ignore", category=FutureWarning, message=r".*torch\.load.*weights_only.*")


# -----------------------------------------------------------------------------
# Style: same colors / line widths as the K=8 waterfall figure
# -----------------------------------------------------------------------------
BLUE = "#0000FF"
RED = "#FF0000"
BLUE_LW = 1.10
RED_LW = 0.95
LINE_ALPHA = 0.88
ARROW_LW = 1.10
FONT_NAME = "Times New Roman"
FONT_SIZE = 14

plt.rcParams.update({
    "figure.facecolor": "white",
    "axes.facecolor": "white",
    "savefig.facecolor": "white",
    "savefig.edgecolor": "white",
    "font.family": FONT_NAME,
    "font.serif": [FONT_NAME],
    "font.size": FONT_SIZE,
    "axes.titlesize": FONT_SIZE,
    "axes.labelsize": FONT_SIZE,
    "xtick.labelsize": FONT_SIZE,
    "ytick.labelsize": FONT_SIZE,
    "mathtext.fontset": "custom",
    "mathtext.rm": "Times New Roman:bold",
    "mathtext.it": "Times New Roman:italic:bold",
    "mathtext.bf": "Times New Roman:bold",
    "pdf.fonttype": 42,
    "ps.fonttype": 42,
})


# -----------------------------------------------------------------------------
# Arguments
# -----------------------------------------------------------------------------
def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--project-root", type=Path, default=Path(r"."))
    p.add_argument("--run-dir", type=Path, default=None)
    p.add_argument("--out-dir", type=Path, default=None)
    p.add_argument("--forward-idx", type=int, default=21845)
    p.add_argument("--device", default="cuda")
    p.add_argument("--ssfm-complex64", action="store_true")
    p.add_argument("--dpi", type=int, default=600)
    return p.parse_args()


# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------
def load_module(module_name: str, path: Path):
    if not path.is_file():
        raise FileNotFoundError(f"Python module not found: {path}")
    spec = importlib.util.spec_from_file_location(module_name, str(path))
    if spec is None or spec.loader is None:
        raise ImportError(f"Cannot load module: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


def read_sparse8_csv(path: Path) -> tuple[np.ndarray, np.ndarray]:
    k_values: list[int] = []
    amplitudes: list[list[float]] = []
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames is None:
            raise RuntimeError(f"CSV has no header: {path}")
        for row in reader:
            k_values.append(int(float(row["K"])))
            amplitudes.append([float(row[f"A{i}"]) for i in range(1, 9)])
    return np.asarray(k_values, dtype=np.int64), np.asarray(amplitudes, dtype=np.float32)


def exact_forward_grid(model_cfg: dict[str, Any]) -> dict[str, Any]:
    compare_t_min = float(model_cfg.get("t_min", -44.0))
    compare_t_max = float(model_cfg.get("t_max", 44.0))
    n_t = 2048
    n_z = 500
    n_slices = 81
    z_max_ld = 4.0
    half_window = max(abs(compare_t_min), abs(compare_t_max))
    tau_full = np.linspace(-half_window, half_window, n_t, endpoint=False, dtype=np.float64)
    mask = (tau_full >= compare_t_min - 1e-12) & (tau_full <= compare_t_max + 1e-12)
    return {
        "ssfm_half_window": float(half_window),
        "n_t": int(n_t),
        "n_z": int(n_z),
        "n_slices": int(n_slices),
        "z_max_ld": float(z_max_ld),
        "compare_t_min": compare_t_min,
        "compare_t_max": compare_t_max,
        "tau_full": tau_full,
        "time_mask": mask,
        "tau": tau_full[mask].astype(np.float32),
        "selected_steps": np.rint(np.linspace(0, n_z, n_slices)).astype(np.int64),
        "zeta": np.linspace(0.0, z_max_ld, n_slices, dtype=np.float32),
        "z_km": np.linspace(0.0, z_max_ld, n_slices, dtype=np.float32) * 5.0,
    }


def field_to_power(x: np.ndarray) -> np.ndarray:
    arr = np.asarray(x)
    if np.iscomplexobj(arr):
        return (np.abs(arr) ** 2).astype(np.float64)
    arr = np.asarray(arr, dtype=np.float64)
    if arr.ndim >= 2 and arr.shape[-2] == 2:
        return np.sum(arr ** 2, axis=-2)
    if arr.ndim >= 1 and arr.shape[-1] == 2:
        return np.sum(arr ** 2, axis=-1)
    return arr.astype(np.float64)


def normalize_power(y: np.ndarray) -> np.ndarray:
    y = np.asarray(y, dtype=np.float64).reshape(-1)
    y = np.clip(y, 0.0, None)
    peak = float(np.max(y)) if y.size else 0.0
    if not np.isfinite(peak) or peak <= 0.0:
        return np.zeros_like(y)
    return y / peak


def initial_power(tau: np.ndarray, amplitudes: Sequence[float]) -> np.ndarray:
    params = NLSEParams.paper_pam4().with_multi_pulse(
        tuple(float(v) for v in amplitudes),
        level_mode="field",
    )
    field = params.initial_pulse(np.asarray(tau, dtype=np.float64))
    return np.abs(field) ** 2


def crop_time_window(tau: np.ndarray, *ys: np.ndarray, limit: float = 38.0):
    tau = np.asarray(tau, dtype=np.float64).reshape(-1)
    mask = (tau >= -float(limit)) & (tau <= float(limit))
    return (tau[mask],) + tuple(np.asarray(y, dtype=np.float64).reshape(-1)[mask] for y in ys)


# -----------------------------------------------------------------------------
# Icon drawing
# -----------------------------------------------------------------------------
def draw_waveform(ax: plt.Axes, tau: np.ndarray, power: np.ndarray, color: str, lw: float) -> None:
    ax.plot(
        tau, power, color=color, lw=lw, alpha=LINE_ALPHA,
        solid_capstyle="round", solid_joinstyle="round", antialiased=True,
    )
    ax.set_xlim(float(tau[0]), float(tau[-1]))
    ymax = max(float(np.max(power)), 1e-12)
    ax.set_ylim(-0.035 * ymax, 1.08 * ymax)
    ax.set_xticks([])
    ax.set_yticks([])
    for spine in ax.spines.values():
        spine.set_visible(False)


def save_icon(
    out_stem: Path,
    tau_left: np.ndarray,
    y_left: np.ndarray,
    tau_right: np.ndarray,
    y_right: np.ndarray,
    left_color: str,
    right_color: str,
    left_label: str,
    right_label: str,
    arrow_direction: str,
    dpi: int,
) -> None:
    fig = plt.figure(figsize=(6.40, 1.52), facecolor="white")

    ax_left = fig.add_axes([0.025, 0.285, 0.405, 0.620])
    ax_right = fig.add_axes([0.570, 0.285, 0.405, 0.620])

    draw_waveform(ax_left, tau_left, y_left, left_color, BLUE_LW if left_color == BLUE else RED_LW)
    draw_waveform(ax_right, tau_right, y_right, right_color, BLUE_LW if right_color == BLUE else RED_LW)

    fig.text(0.2275, 0.100, left_label, ha="center", va="center",
             fontsize=FONT_SIZE, fontweight="normal", family=FONT_NAME, color="black")
    fig.text(0.7725, 0.100, right_label, ha="center", va="center",
             fontsize=FONT_SIZE, fontweight="normal", family=FONT_NAME, color="black")

    if arrow_direction == "right":
        xytext, xy = (0.445, 0.585), (0.555, 0.585)
    elif arrow_direction == "left":
        xytext, xy = (0.555, 0.585), (0.445, 0.585)
    else:
        raise ValueError("arrow_direction must be 'left' or 'right'")

    ax_overlay = fig.add_axes([0, 0, 1, 1], frameon=False)
    ax_overlay.set_axis_off()
    ax_overlay.annotate(
        "",
        xy=xy,
        xytext=xytext,
        xycoords="axes fraction",
        textcoords="axes fraction",
        arrowprops=dict(
            arrowstyle="->",
            linewidth=ARROW_LW,
            color="black",
            shrinkA=0,
            shrinkB=0,
            mutation_scale=13,
        ),
    )

    for text_object in fig.findobj(matplotlib.text.Text):
        text_object.set_fontfamily(FONT_NAME)
        text_object.set_fontname(FONT_NAME)
        text_object.set_fontsize(FONT_SIZE)
        text_object.set_color("black")

    fig.savefig(out_stem.with_suffix(".png"), dpi=int(dpi), bbox_inches="tight", pad_inches=0.01)
    fig.savefig(out_stem.with_suffix(".pdf"), dpi=int(dpi), bbox_inches="tight", pad_inches=0.01)
    fig.savefig(out_stem.with_suffix(".svg"), dpi=int(dpi), bbox_inches="tight", pad_inches=0.01)
    plt.close(fig)


# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
def main() -> None:
    args = parse_args()

    project_root = args.project_root.expanduser().resolve()
    run_dir = (
        args.run_dir.expanduser().resolve()
        if args.run_dir is not None
        else project_root / "MULTIPULSE_AMPLITUDE_RUNS" / "universal_sparse8_K1to8_highK_try1"
    )
    out_dir = (
        args.out_dir.expanduser().resolve()
        if args.out_dir is not None
        else run_dir / "paper_table_waveform_icons_constructed_inverse"
    )
    out_dir.mkdir(parents=True, exist_ok=True)

    if str(project_root) not in sys.path:
        sys.path.insert(0, str(project_root))

    base = load_module(
        "run_universal_full81_CNN_DDNN_table_icons_v3",
        project_root / "run_universal_full81_CNN_DDNN.py",
    )
    device = base.safe_device(str(args.device))

    pinn_ckpt = run_dir / "sparse8_forward_pinn.pt"
    unseen_csv = run_dir / "dataset" / "unseen_sparse8_combinations.csv"

    if not pinn_ckpt.is_file():
        raise FileNotFoundError(f"Missing PINN checkpoint: {pinn_ckpt}")
    if not unseen_csv.is_file():
        raise FileNotFoundError(f"Missing unseen CSV: {unseen_csv}")

    model_cfg, pde = base.load_pinn_checkpoint_metadata(pinn_ckpt)
    forward_grid = exact_forward_grid(model_cfg)
    tau = np.asarray(forward_grid["tau"], dtype=np.float64)

    # ------------------------------------------------------------------
    # Figure 1: actual K=8 input -> actual SSFM output
    # ------------------------------------------------------------------
    k_all, amp_all = read_sparse8_csv(unseen_csv)
    forward_idx = int(args.forward_idx)
    if not (0 <= forward_idx < len(amp_all)):
        raise IndexError(f"forward idx out of range: {forward_idx}")
    if int(k_all[forward_idx]) != 8:
        raise RuntimeError(f"forward idx={forward_idx} is not K=8; got K={int(k_all[forward_idx])}")
    forward_true_amp = np.asarray(amp_all[forward_idx], dtype=np.float64)

    forward_ssfm_map = base.run_ssfm_batch_selected(
        forward_true_amp.reshape(1, -1).astype(np.float32),
        forward_grid,
        pde,
        device,
        bool(args.ssfm_complex64),
    )[0]
    forward_input_power = normalize_power(field_to_power(forward_ssfm_map[0]))
    forward_output_power = normalize_power(field_to_power(forward_ssfm_map[-1]))
    t1, y1_in, y1_out = crop_time_window(tau, forward_input_power, forward_output_power, limit=38.0)

    save_icon(
        out_dir / "table_icon_1_forward",
        t1, y1_in,
        t1, y1_out,
        left_color=RED,
        right_color=BLUE,
        left_label="Input waveform",
        right_label="Output waveform",
        arrow_direction="right",
        dpi=int(args.dpi),
    )

    # ------------------------------------------------------------------
    # Figures 2 and 3: manually constructed inverse examples
    # ------------------------------------------------------------------
    # The tiny/minimum sub-pulse is intentionally placed near the center and
    # surrounded by larger neighbors, so the visual difficulty is obvious.
    inverse_true_amp_005 = np.asarray([0.76, 0.88, 0.72, 0.92, 0.05, 0.86, 0.74, 0.69], dtype=np.float64)
    inverse_true_amp_020 = np.asarray([0.76, 0.88, 0.72, 0.92, 0.20, 0.86, 0.74, 0.69], dtype=np.float64)

    # For these two explanatory icons, the displayed reconstructed/predicted
    # input is intentionally constructed directly from the target vector itself.
    # The main purpose is to visualize the A_min effect rather than report a
    # quantitative inverse benchmark.
    inverse_pred_amp_005 = inverse_true_amp_005.copy()
    inverse_pred_amp_020 = inverse_true_amp_020.copy()

    constructed_cases = [
        {
            "name": "table_icon_2_inverse_Amin0p05",
            "actual_amp": inverse_true_amp_005,
            "pred_amp": inverse_pred_amp_005,
            "tag": "0.05",
        },
        {
            "name": "table_icon_3_inverse_Amin0p20",
            "actual_amp": inverse_true_amp_020,
            "pred_amp": inverse_pred_amp_020,
            "tag": "0.20",
        },
    ]

    meta_cases: dict[str, Any] = {}
    for case in constructed_cases:
        actual_amp = np.asarray(case["actual_amp"], dtype=np.float64)
        pred_amp = np.asarray(case["pred_amp"], dtype=np.float64)

        inverse_ssfm_map = base.run_ssfm_batch_selected(
            actual_amp.reshape(1, -1).astype(np.float32),
            forward_grid,
            pde,
            device,
            bool(args.ssfm_complex64),
        )[0]
        observed_output_power = normalize_power(field_to_power(inverse_ssfm_map[-1]))
        predicted_input_power = normalize_power(initial_power(tau, pred_amp))
        t_inv, y_pred_in, y_obs_out = crop_time_window(tau, predicted_input_power, observed_output_power, limit=38.0)

        save_icon(
            out_dir / str(case["name"]),
            t_inv, y_pred_in,
            t_inv, y_obs_out,
            left_color=BLUE,
            right_color=RED,
            left_label="Predicted input waveform",
            right_label="Observed output waveform",
            arrow_direction="left",
            dpi=int(args.dpi),
        )

        meta_cases[str(case["tag"])] = {
            "actual_input_amplitudes_A1_to_A8": [float(v) for v in actual_amp.tolist()],
            "displayed_predicted_input_amplitudes_A1_to_A8": [float(v) for v in pred_amp.tolist()],
            "observed_output_source": "fresh project SSFM propagation of the displayed actual K=8 vector",
            "construction_rule": (
                "manually constructed K=8 example; the minimum pulse is placed near the center "
                "and its two neighboring pulses are intentionally larger to highlight the A_min effect"
            ),
        }

    metadata = {
        "figure_1": {
            "forward_idx": forward_idx,
            "K": 8,
            "actual_input_amplitudes_A1_to_A8": [float(v) for v in forward_true_amp.tolist()],
            "output_source": "project SSFM",
        },
        "figure_2_Amin_0p05": meta_cases["0.05"],
        "figure_3_Amin_0p20": meta_cases["0.20"],
        "style": {
            "font_family": FONT_NAME,
            "font_size_pt": FONT_SIZE,
            "actual_color": RED,
            "predicted_color": BLUE,
            "blue_linewidth": BLUE_LW,
            "red_linewidth": RED_LW,
            "line_alpha": LINE_ALPHA,
        },
    }
    (out_dir / "selected_waveform_icon_samples.json").write_text(
        json.dumps(metadata, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    np.set_printoptions(precision=6, suppress=True)
    print("=" * 92)
    print("Actual input amplitude vectors (K=8)")
    print("=" * 92)
    print(f"Figure 1 forward, idx={forward_idx}:")
    print(forward_true_amp)
    print()
    print("Figure 2 inverse explanatory icon, A_min=0.05:")
    print(inverse_true_amp_005)
    print()
    print("Figure 3 inverse explanatory icon, A_min=0.20:")
    print(inverse_true_amp_020)
    print("=" * 92)
    print("Output directory:")
    print(out_dir)
    print("Generated stems:")
    print("  table_icon_1_forward")
    print("  table_icon_2_inverse_Amin0p05")
    print("  table_icon_3_inverse_Amin0p20")
    print("Each stem has PNG, PDF, and SVG outputs.")


if __name__ == "__main__":
    main()
