# -*- coding: utf-8 -*-
"""
evaluate_random_continuous_inverse_CNN_DDNN_v2.py

Formal continuous-random inverse comparison for the already-trained inverse CNN
and the frozen-forward same-architecture DDNN.

The experiment follows the PINN random-continuous inverse definition exactly:
  * 10 amplitude vectors A ~ Uniform([0,1]^M), sample_seed=2027 by default;
  * the physical target waveform is generated by SSFM;
  * PINN/DDNN use four independent restarts per target and select each target's
    historical lowest-loss restart;
  * the inverse objective is evaluated on the same 512-point terminal grid used
    by the PINN random-continuous script;
  * the selected amplitudes are propagated by SSFM again for a physical
    backcheck.

CNN is a deterministic direct inverse map h(4LD,t)->h(0,t), so restart is not
applicable. Continuous amplitudes are decoded from the predicted initial field
by least squares on the known Gaussian pulse basis.

Output locations deliberately remain under the previous method roots:
  CNN:
    <run>/endpoint_all_seen_resume_v7/cnn_direct/cnn_inverse/
        random_continuous_0to1/seed_2027/
  DDNN (replaces the old PAM4 inverse after cleanup):
    <run>/endpoint_all_seen_resume_v7/ddnn_same_architecture/
        inverse/seed_2026/

The shared amplitudes and PINN-compatible 512-point SSFM observations are kept
in the existing PINN random-continuous dataset folder:
  <run>/inverse/05_random_continuous_target_blind_0to1/
      random_continuous_ssfm_N10_seed2027/

Python 3.8 compatible.
"""
from __future__ import annotations

import argparse
import gc
import hashlib
import importlib.util
import json
import math
import os
import random
import shutil
import sys
import time
import uuid
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd

SCRIPT_VERSION = "RANDOM_CONTINUOUS_INVERSE_CNN_DDNN_V2_PINN_COMPAT_20260705"
TOLERANCES = ((0.01, "0p01"), (0.025, "0p025"), (0.05, "0p05"))


def set_seed(seed: int, torch_module: Any) -> None:
    random.seed(int(seed))
    np.random.seed(int(seed))
    torch_module.manual_seed(int(seed))
    if torch_module.cuda.is_available():
        torch_module.cuda.manual_seed_all(int(seed))


def read_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, value: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2), encoding="utf-8")


def combo_text(values: Sequence[float]) -> str:
    return ";".join("%.9g" % float(x) for x in values)


def case_digest(amplitudes: np.ndarray) -> str:
    array = np.asarray(amplitudes, dtype=np.float32, order="C")
    return hashlib.sha256(array.tobytes()).hexdigest()


def iter_batches(n: int, batch_size: int) -> Iterable[Tuple[int, int]]:
    size = max(1, int(batch_size))
    for start in range(0, int(n), size):
        yield start, min(int(n), start + size)


def load_v10b_runtime(project_root: Path, script_name: str) -> Tuple[Any, Any, Any]:
    project_root = project_root.resolve()
    if str(project_root) not in sys.path:
        sys.path.insert(0, str(project_root))
    requested = project_root / script_name
    if not requested.exists():
        candidates = sorted(project_root.glob(
            "run_fixedM_endpoint_CNN_samearch_DDNN_full_sampling_resume_v10b_windowsfix*.py"
        ))
        exact = [path for path in candidates if "(" not in path.name]
        requested = exact[0] if exact else (candidates[0] if candidates else requested)
    if not requested.exists():
        raise FileNotFoundError("Cannot find V10B workflow script: %s" % requested)
    spec = importlib.util.spec_from_file_location("endpoint_v10b_runtime_v2", str(requested))
    if spec is None or spec.loader is None:
        raise ImportError("Cannot import V10B script: %s" % requested)
    unified = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(unified)
    cnn = unified._load_embedded_module("_random_inverse_cnn_v2", unified._CNN_SOURCE_B85)
    ddnn = unified._load_embedded_module("_random_inverse_ddnn_v2", unified._DDNN_SOURCE_B85)
    unified._install_v7_patches(cnn, ddnn)
    cnn.base.find_run_dir = unified._find_run_dir_highest_ratio
    ddnn.find_run_dir = unified._find_run_dir_highest_ratio
    print("[runtime] V10B:", requested, flush=True)
    return unified, cnn, ddnn


def rel_field_l2(pred: np.ndarray, target: np.ndarray) -> np.ndarray:
    pred64 = np.asarray(pred, dtype=np.float64)
    target64 = np.asarray(target, dtype=np.float64)
    axes = tuple(range(1, pred64.ndim))
    num = np.sum((pred64 - target64) ** 2, axis=axes)
    den = np.sum(target64 ** 2, axis=axes) + 1e-300
    return np.sqrt(num / den)


def rel_power_l2(pred: np.ndarray, target: np.ndarray) -> np.ndarray:
    pred64 = np.asarray(pred, dtype=np.float64)
    target64 = np.asarray(target, dtype=np.float64)
    if pred64.ndim != 3 or pred64.shape[1] != 2:
        raise ValueError("Expected complex field shape [N,2,T], got %s" % (pred64.shape,))
    pred_power = np.sum(pred64 ** 2, axis=1)
    target_power = np.sum(target64 ** 2, axis=1)
    num = np.sum((pred_power - target_power) ** 2, axis=1)
    den = np.sum(target_power ** 2, axis=1) + 1e-300
    return np.sqrt(num / den)


def interpolate_complex_batch(
    source_tau: np.ndarray,
    source_field: np.ndarray,
    target_tau: np.ndarray,
) -> np.ndarray:
    source_tau = np.asarray(source_tau, dtype=np.float64)
    target_tau = np.asarray(target_tau, dtype=np.float64)
    source_field = np.asarray(source_field, dtype=np.float32)
    out = np.empty((source_field.shape[0], 2, len(target_tau)), dtype=np.float32)
    for i in range(source_field.shape[0]):
        out[i, 0] = np.interp(target_tau, source_tau, source_field[i, 0]).astype(np.float32)
        out[i, 1] = np.interp(target_tau, source_tau, source_field[i, 1]).astype(np.float32)
    return out


def gaussian_basis(tau: np.ndarray, centers: Sequence[float]) -> np.ndarray:
    tau = np.asarray(tau, dtype=np.float64)
    return np.stack([
        np.exp(-0.5 * (tau - float(center)) ** 2) for center in centers
    ], axis=1)


def decode_amplitudes_from_initial_waveforms(
    waveforms: np.ndarray,
    tau: np.ndarray,
    centers: Sequence[float],
) -> np.ndarray:
    basis = gaussian_basis(tau, centers)
    predicted = np.asarray(waveforms, dtype=np.float64)
    decoded: List[np.ndarray] = []
    for index in range(len(predicted)):
        values, _, _, _ = np.linalg.lstsq(basis, predicted[index, 0], rcond=None)
        decoded.append(np.clip(values, 0.0, 1.0))
    return np.asarray(decoded, dtype=np.float32)


def amplitude_metrics(pred: np.ndarray, true: np.ndarray) -> Dict[str, np.ndarray]:
    pred64 = np.asarray(pred, dtype=np.float64)
    true64 = np.asarray(true, dtype=np.float64)
    absolute = np.abs(pred64 - true64)
    result: Dict[str, np.ndarray] = {
        "amplitude_mae": np.mean(absolute, axis=1),
        "amplitude_rmse": np.sqrt(np.mean((pred64 - true64) ** 2, axis=1)),
        "amplitude_max_abs_error": np.max(absolute, axis=1),
    }
    for tolerance, suffix in TOLERANCES:
        result["all_pulses_within_%s" % suffix] = np.all(
            absolute <= float(tolerance), axis=1
        ).astype(np.float64)
        result["per_pulse_within_%s" % suffix] = np.mean(
            absolute <= float(tolerance), axis=1
        )
    return result


def atomic_torch_save(torch_module: Any, payload: Dict[str, Any], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".pid%d.%s.tmp" % (os.getpid(), uuid.uuid4().hex))
    torch_module.save(payload, str(temporary))
    last_error: Optional[BaseException] = None
    for attempt in range(20):
        try:
            os.replace(str(temporary), str(path))
            return
        except PermissionError as exc:
            last_error = exc
            time.sleep(0.15 * (attempt + 1))
    fallback = path.with_name(path.stem + ".fallback_%d_%s.pt" % (os.getpid(), uuid.uuid4().hex[:8]))
    os.replace(str(temporary), str(fallback))
    print("[checkpoint-warning] canonical path locked; fallback saved:", fallback, flush=True)
    if last_error is not None:
        print("[checkpoint-warning] last error:", repr(last_error), flush=True)


def newest_resume_path(canonical: Path) -> Optional[Path]:
    candidates: List[Path] = []
    if canonical.exists():
        candidates.append(canonical)
    candidates.extend(canonical.parent.glob(canonical.stem + ".fallback_*.pt"))
    return max(candidates, key=lambda path: path.stat().st_mtime) if candidates else None


def shared_pinn_dataset_root(run_dir: Path, n_samples: int, sample_seed: int) -> Path:
    return (
        run_dir / "inverse" / "05_random_continuous_target_blind_0to1" /
        ("random_continuous_ssfm_N%d_seed%d" % (int(n_samples), int(sample_seed)))
    )


def _exact_pinn_amplitudes(M: int, n_samples: int, sample_seed: int) -> np.ndarray:
    rng = np.random.default_rng(int(sample_seed))
    amplitudes = rng.uniform(0.0, 1.0, size=(int(n_samples), int(M))).astype(np.float32)
    return np.clip(amplitudes, 1e-6, 1.0 - 1e-6)


def generate_or_load_shared_cases(
    *,
    run_dir: Path,
    M: int,
    n_samples: int,
    sample_seed: int,
    inverse_input_points: int,
    ddnn: Any,
    device: Any,
    ssfm_batch_size: int,
    force_full_cache: bool,
) -> Dict[str, Any]:
    root = shared_pinn_dataset_root(run_dir, n_samples, sample_seed)
    root.mkdir(parents=True, exist_ok=True)
    amplitude_path = root / "true_amplitudes.npy"
    amplitude_csv = root / "true_amplitudes.csv"
    expected = _exact_pinn_amplitudes(M, n_samples, sample_seed)
    if amplitude_path.exists():
        amplitudes = np.asarray(np.load(str(amplitude_path)), dtype=np.float32)
        if amplitudes.shape != expected.shape:
            raise RuntimeError(
                "Existing PINN random amplitudes have shape %s, expected %s"
                % (amplitudes.shape, expected.shape)
            )
        if not np.allclose(amplitudes, expected, atol=1e-7, rtol=0.0):
            raise RuntimeError(
                "Existing PINN random amplitudes do not match sample_seed=%d. "
                "Do not mix different random cases." % int(sample_seed)
            )
        print("[shared cases] reuse PINN amplitudes:", amplitude_path, flush=True)
    else:
        amplitudes = expected
        np.save(str(amplitude_path), amplitudes)
        frame = pd.DataFrame(amplitudes, columns=["A%d" % (j + 1) for j in range(M)])
        frame.insert(0, "sample_rank", np.arange(n_samples, dtype=np.int64))
        frame.to_csv(amplitude_csv, index=False, encoding="utf-8-sig")
        print("[shared cases] created PINN-compatible amplitudes:", amplitude_path, flush=True)

    digest = case_digest(amplitudes)
    full_cache = root / "cnn_ddnn_full_grid_cases.npz"
    full_manifest = root / "cnn_ddnn_full_grid_manifest.json"
    use_cache = full_cache.exists() and full_manifest.exists() and not bool(force_full_cache)
    if use_cache:
        manifest = read_json(full_manifest)
        if manifest.get("case_digest_sha256") != digest:
            use_cache = False
    if use_cache:
        payload = np.load(str(full_cache))
        tau_full = np.asarray(payload["tau_full"], dtype=np.float32)
        true_initial_full = np.asarray(payload["true_initial_full"], dtype=np.float32)
        target_terminal_full = np.asarray(payload["target_terminal_full"], dtype=np.float32)
        z_final = float(np.asarray(payload["z_final"]).reshape(-1)[0])
        print("[shared cases] reuse full-grid SSFM cache:", full_cache, flush=True)
    else:
        target_parts: List[np.ndarray] = []
        tau_full: Optional[np.ndarray] = None
        z_final: Optional[float] = None
        build_start = time.perf_counter()
        for start, end in iter_batches(n_samples, ssfm_batch_size):
            part, tau_part, z_part = ddnn.make_ssfm_terminal_batch(
                run_dir, amplitudes[start:end], device
            )
            target_parts.append(np.asarray(part, dtype=np.float32))
            tau_full = np.asarray(tau_part, dtype=np.float32)
            z_final = float(z_part)
        if tau_full is None or z_final is None:
            raise RuntimeError("SSFM generation returned no full-grid data.")
        target_terminal_full = np.concatenate(target_parts, axis=0)
        true_initial_full = ddnn.make_initial_waveforms_numpy(amplitudes, tau_full)
        np.savez_compressed(
            str(full_cache),
            amplitudes=amplitudes,
            tau_full=tau_full,
            true_initial_full=true_initial_full,
            target_terminal_full=target_terminal_full,
            z_final=np.asarray([z_final], dtype=np.float32),
        )
        write_json(full_manifest, {
            "script_version": SCRIPT_VERSION,
            "case_digest_sha256": digest,
            "M": int(M),
            "n_samples": int(n_samples),
            "sample_seed": int(sample_seed),
            "n_time_full": int(len(tau_full)),
            "build_elapsed_sec": float(time.perf_counter() - build_start),
            "purpose": "same physical random continuous targets for CNN/DDNN and PINN",
        })
        print("[shared cases] saved full-grid SSFM cache:", full_cache, flush=True)

    # Prefer the exact 512-point PINN observation if it already exists.
    tau_path = root / "tau_input.npy"
    real_path = root / "Y_terminal_real.npy"
    imag_path = root / "Y_terminal_imag.npy"
    power_path = root / "Y_terminal_power.npy"
    if tau_path.exists() and real_path.exists() and imag_path.exists():
        tau_inverse = np.asarray(np.load(str(tau_path)), dtype=np.float32)
        real = np.asarray(np.load(str(real_path)), dtype=np.float32)
        imag = np.asarray(np.load(str(imag_path)), dtype=np.float32)
        target_terminal_inverse = np.stack([real, imag], axis=1)
        if target_terminal_inverse.shape != (n_samples, 2, len(tau_inverse)):
            raise RuntimeError("Bad existing PINN terminal dataset shape: %s" % (target_terminal_inverse.shape,))
        print("[shared cases] reuse exact PINN terminal grid:", tau_path, flush=True)
    else:
        tau_inverse = np.linspace(
            float(tau_full[0]), float(tau_full[-1]), int(inverse_input_points), dtype=np.float32
        )
        target_terminal_inverse = interpolate_complex_batch(
            tau_full, target_terminal_full, tau_inverse
        )
        np.save(str(tau_path), tau_inverse)
        np.save(str(real_path), target_terminal_inverse[:, 0])
        np.save(str(imag_path), target_terminal_inverse[:, 1])
        np.save(str(power_path), np.sum(target_terminal_inverse ** 2, axis=1).astype(np.float32))
        print("[shared cases] created PINN-compatible terminal grid:", tau_path, flush=True)

    return {
        "root": root,
        "case_digest": digest,
        "amplitudes": amplitudes,
        "tau_full": tau_full,
        "true_initial_full": true_initial_full,
        "target_terminal_full": target_terminal_full,
        "tau_inverse": tau_inverse,
        "target_terminal_inverse": target_terminal_inverse,
        "z_final": float(z_final),
    }


def run_ssfm_for_amplitudes(
    run_dir: Path,
    amplitudes: np.ndarray,
    ddnn: Any,
    device: Any,
    batch_size: int,
) -> Tuple[np.ndarray, np.ndarray]:
    parts: List[np.ndarray] = []
    tau: Optional[np.ndarray] = None
    for start, end in iter_batches(len(amplitudes), batch_size):
        part, tau_part, _ = ddnn.make_ssfm_terminal_batch(
            run_dir, np.asarray(amplitudes[start:end], dtype=np.float32), device
        )
        parts.append(np.asarray(part, dtype=np.float32))
        tau = np.asarray(tau_part, dtype=np.float32)
    if tau is None:
        raise RuntimeError("No SSFM backcheck data generated.")
    return np.concatenate(parts, axis=0), tau


def common_rows(
    *,
    M: int,
    method: str,
    true_amplitudes: np.ndarray,
    predicted_amplitudes: np.ndarray,
    true_initial_full: np.ndarray,
    predicted_initial_full: np.ndarray,
    target_terminal_inverse: np.ndarray,
    ssfm_terminal_inverse: np.ndarray,
    target_terminal_full: np.ndarray,
    ssfm_terminal_full: np.ndarray,
    inverse_elapsed_sec: float,
    selected_restart: Optional[np.ndarray] = None,
    selected_best_epoch: Optional[np.ndarray] = None,
    selected_objective: Optional[np.ndarray] = None,
    model_terminal_inverse: Optional[np.ndarray] = None,
    model_terminal_full: Optional[np.ndarray] = None,
) -> List[Dict[str, Any]]:
    amp = amplitude_metrics(predicted_amplitudes, true_amplitudes)
    input_field = rel_field_l2(predicted_initial_full, true_initial_full)
    input_power = rel_power_l2(predicted_initial_full, true_initial_full)
    ssfm_complex = rel_field_l2(ssfm_terminal_inverse, target_terminal_inverse)
    ssfm_power = rel_power_l2(ssfm_terminal_inverse, target_terminal_inverse)
    ssfm_complex_full = rel_field_l2(ssfm_terminal_full, target_terminal_full)
    ssfm_power_full = rel_power_l2(ssfm_terminal_full, target_terminal_full)
    if model_terminal_inverse is not None:
        model_complex = rel_field_l2(model_terminal_inverse, target_terminal_inverse)
        model_power = rel_power_l2(model_terminal_inverse, target_terminal_inverse)
    else:
        model_complex = np.full(len(true_amplitudes), np.nan)
        model_power = np.full(len(true_amplitudes), np.nan)
    if model_terminal_full is not None:
        model_complex_full = rel_field_l2(model_terminal_full, target_terminal_full)
        model_power_full = rel_power_l2(model_terminal_full, target_terminal_full)
    else:
        model_complex_full = np.full(len(true_amplitudes), np.nan)
        model_power_full = np.full(len(true_amplitudes), np.nan)

    rows: List[Dict[str, Any]] = []
    for i in range(len(true_amplitudes)):
        objective = float(selected_objective[i]) if selected_objective is not None else float("nan")
        row: Dict[str, Any] = {
            "sample_rank": int(i),
            "M": int(M),
            "method": method,
            "true_amplitudes": combo_text(true_amplitudes[i]),
            "pred_amplitudes": combo_text(predicted_amplitudes[i]),
            "amplitude_mae": float(amp["amplitude_mae"][i]),
            "amplitude_rmse": float(amp["amplitude_rmse"][i]),
            "amplitude_max_abs_error": float(amp["amplitude_max_abs_error"][i]),
            "initial_rel_l2_field": float(input_field[i]),
            "initial_rel_l2_power": float(input_power[i]),
            "best_restart_forward_inverse_loss": objective,
            "best_restart_forward_inverse_rel_l2": (
                float(math.sqrt(max(0.0, objective))) if np.isfinite(objective) else float("nan")
            ),
            "forward_inverse_complex_rel_l2": float(model_complex[i]),
            "forward_inverse_power_rel_l2": float(model_power[i]),
            "forward_inverse_complex_rel_l2_fullgrid": float(model_complex_full[i]),
            "forward_inverse_power_rel_l2_fullgrid": float(model_power_full[i]),
            "ssfm_reconstruction_complex_rel_l2": float(ssfm_complex[i]),
            "ssfm_reconstruction_power_rel_l2": float(ssfm_power[i]),
            "ssfm_reconstruction_output_rel_l2": float(ssfm_complex[i]),
            "ssfm_reconstruction_complex_rel_l2_fullgrid": float(ssfm_complex_full[i]),
            "ssfm_reconstruction_power_rel_l2_fullgrid": float(ssfm_power_full[i]),
            "selected_restart": int(selected_restart[i]) if selected_restart is not None else -1,
            "best_epoch": int(selected_best_epoch[i]) if selected_best_epoch is not None else 0,
            "inverse_sec_per_sample": float(inverse_elapsed_sec / max(1, len(true_amplitudes))),
        }
        for _, suffix in TOLERANCES:
            row["all_pulses_within_%s" % suffix] = float(amp["all_pulses_within_%s" % suffix][i])
            row["per_pulse_within_%s" % suffix] = float(amp["per_pulse_within_%s" % suffix][i])
        rows.append(row)
    return rows


def summarize_rows(
    rows: List[Dict[str, Any]],
    checkpoint: Path,
    extra: Dict[str, Any],
) -> Dict[str, Any]:
    frame = pd.DataFrame(rows)
    summary: Dict[str, Any] = {
        "script_version": SCRIPT_VERSION,
        "method": rows[0]["method"] if rows else "",
        "M": int(rows[0]["M"]) if rows else 0,
        "n_samples": int(len(rows)),
        "checkpoint": str(checkpoint),
    }
    metrics = [
        "amplitude_mae", "amplitude_rmse", "amplitude_max_abs_error",
        "initial_rel_l2_field", "initial_rel_l2_power",
        "best_restart_forward_inverse_loss", "best_restart_forward_inverse_rel_l2",
        "forward_inverse_complex_rel_l2", "forward_inverse_power_rel_l2",
        "forward_inverse_complex_rel_l2_fullgrid", "forward_inverse_power_rel_l2_fullgrid",
        "ssfm_reconstruction_output_rel_l2", "ssfm_reconstruction_complex_rel_l2",
        "ssfm_reconstruction_power_rel_l2",
        "ssfm_reconstruction_complex_rel_l2_fullgrid",
        "ssfm_reconstruction_power_rel_l2_fullgrid",
        "inverse_sec_per_sample",
    ]
    for _, suffix in TOLERANCES:
        metrics.extend(["all_pulses_within_%s" % suffix, "per_pulse_within_%s" % suffix])
    for metric in metrics:
        if metric in frame.columns:
            values = pd.to_numeric(frame[metric], errors="coerce")
            summary[metric + "_mean"] = float(values.mean())
            summary[metric + "_std"] = float(values.std(ddof=0))
    if "ssfm_reconstruction_output_rel_l2" in frame.columns:
        values = pd.to_numeric(frame["ssfm_reconstruction_output_rel_l2"], errors="coerce").dropna()
        if len(values):
            summary["ssfm_reconstruction_output_rel_l2_p95"] = float(np.percentile(values, 95))
            summary["ssfm_reconstruction_output_rel_l2_max"] = float(np.max(values))
    if "best_epoch" in frame.columns:
        values = pd.to_numeric(frame["best_epoch"], errors="coerce").dropna()
        if len(values):
            summary["best_epoch_p50_all_restarts"] = float(np.percentile(values, 50))
            summary["best_epoch_p90_all_restarts"] = float(np.percentile(values, 90))
            summary["best_epoch_max_all_restarts"] = int(np.max(values))
    # PINN-compatible aliases.
    summary["sample_all_pulses_within_0p01_accuracy"] = summary.get("all_pulses_within_0p01_mean")
    summary["sample_all_pulses_within_0p025_accuracy"] = summary.get("all_pulses_within_0p025_mean")
    summary["sample_all_pulses_within_0p05_accuracy"] = summary.get("all_pulses_within_0p05_mean")
    summary["per_pulse_within_0p01_accuracy"] = summary.get("per_pulse_within_0p01_mean")
    summary["per_pulse_within_0p025_accuracy"] = summary.get("per_pulse_within_0p025_mean")
    summary["per_pulse_within_0p05_accuracy"] = summary.get("per_pulse_within_0p05_mean")
    summary["amplitude_mae_mean"] = summary.get("amplitude_mae_mean")
    summary["amplitude_rmse_mean"] = summary.get("amplitude_rmse_mean")
    summary["amplitude_max_abs_error_mean"] = summary.get("amplitude_max_abs_error_mean")
    summary["forward_inverse_complex_rel_l2_mean"] = summary.get("forward_inverse_complex_rel_l2_mean")
    summary["forward_inverse_power_rel_l2_mean"] = summary.get("forward_inverse_power_rel_l2_mean")
    summary["best_restart_forward_inverse_loss_mean"] = summary.get("best_restart_forward_inverse_loss_mean")
    summary["best_restart_forward_inverse_rel_l2_mean"] = summary.get("best_restart_forward_inverse_rel_l2_mean")
    summary["ssfm_reconstruction_output_rel_l2_mean"] = summary.get("ssfm_reconstruction_output_rel_l2_mean")
    summary["ssfm_reconstruction_complex_rel_l2_mean"] = summary.get("ssfm_reconstruction_complex_rel_l2_mean")
    summary["ssfm_reconstruction_power_rel_l2_mean"] = summary.get("ssfm_reconstruction_power_rel_l2_mean")
    summary.update(extra)
    return summary


def run_cnn_inverse(
    *,
    run_dir: Path,
    cases: Dict[str, Any],
    base_output_folder: str,
    source_cnn_folder: str,
    model_seed: int,
    sample_seed: int,
    cnn: Any,
    ddnn: Any,
    device: Any,
    amp_enabled: bool,
    ssfm_batch_size: int,
    force: bool,
) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    output_root = (
        run_dir / base_output_folder / "cnn_direct" / "cnn_inverse" /
        "random_continuous_0to1" / ("seed_%d" % int(sample_seed))
    )
    result_path = output_root / "inverse_results.csv"
    summary_path = output_root / "summary.json"
    if result_path.exists() and summary_path.exists() and not force:
        print("[CNN random inverse] exists, skip:", result_path, flush=True)
        return pd.read_csv(result_path).to_dict("records"), read_json(summary_path)
    if force and output_root.exists():
        shutil.rmtree(output_root)
    output_root.mkdir(parents=True, exist_ok=True)
    checkpoint = (
        run_dir / base_output_folder / "cnn_direct" / "cnn_inverse" /
        "train" / ("seed_%d" % int(model_seed)) / "final" / "final_model.pt"
    )
    if not checkpoint.exists():
        raise FileNotFoundError("Missing inverse CNN checkpoint: %s" % checkpoint)
    metadata = read_json(run_dir / source_cnn_folder / "dataset" / "metadata.json")
    scale = float(metadata.get("field_scale_max_abs_seen", 1.0))
    if not np.isfinite(scale) or scale <= 0.0:
        raise ValueError("Invalid CNN field scale: %s" % scale)
    model, _ = cnn.load_checkpoint(checkpoint, device)
    model.eval()
    start = time.perf_counter()
    with cnn.torch.inference_mode():
        source = cnn.torch.from_numpy(
            np.asarray(cases["target_terminal_full"] / scale, dtype=np.float32)
        ).to(device)
        with cnn.torch.cuda.amp.autocast(enabled=bool(amp_enabled)):
            predicted = model(source)
        predicted_initial = predicted.float().cpu().numpy() * scale
    elapsed = float(time.perf_counter() - start)
    centers = ddnn.pulse_centers_t0(int(cases["amplitudes"].shape[1]))
    predicted_amplitudes = decode_amplitudes_from_initial_waveforms(
        predicted_initial, cases["tau_full"], centers
    )
    back_full, back_tau = run_ssfm_for_amplitudes(
        run_dir, predicted_amplitudes, ddnn, device, ssfm_batch_size
    )
    if not np.allclose(back_tau, cases["tau_full"], atol=1e-7, rtol=0.0):
        raise RuntimeError("CNN SSFM backcheck grid changed unexpectedly.")
    back_inverse = interpolate_complex_batch(
        back_tau, back_full, cases["tau_inverse"]
    )
    rows = common_rows(
        M=int(cases["amplitudes"].shape[1]),
        method="cnn_inverse_direct",
        true_amplitudes=cases["amplitudes"],
        predicted_amplitudes=predicted_amplitudes,
        true_initial_full=cases["true_initial_full"],
        predicted_initial_full=predicted_initial,
        target_terminal_inverse=cases["target_terminal_inverse"],
        ssfm_terminal_inverse=back_inverse,
        target_terminal_full=cases["target_terminal_full"],
        ssfm_terminal_full=back_full,
        inverse_elapsed_sec=elapsed,
    )
    pd.DataFrame(rows).to_csv(result_path, index=False, encoding="utf-8-sig")
    summary = summarize_rows(rows, checkpoint, {
        "experiment_type": "random_continuous_uniform_0_1",
        "case_digest_sha256": cases["case_digest"],
        "shared_pinn_dataset": str(cases["root"]),
        "restarts_per_sample": 0,
        "restart_count": 0,
        "inverse_logic": "deterministic direct terminal-waveform to initial-waveform CNN",
        "amplitude_decoder": "least squares on known Gaussian basis, clipped to [0,1]",
        "terminal_proxy_metric_note": "not applicable to a direct inverse CNN",
        "inverse_runtime_sec_for_method_comparison": elapsed,
        "inverse_runtime_sec_per_sample": float(elapsed / max(1, len(rows))),
    })
    write_json(summary_path, summary)
    print("[CNN random inverse] saved:", result_path, flush=True)
    del model
    gc.collect()
    if device.type == "cuda":
        cnn.torch.cuda.empty_cache()
    return rows, summary


def pinn_compatible_initial_raw(
    sample_count: int,
    restarts: int,
    M: int,
    seed: int,
) -> np.ndarray:
    raw = np.empty((sample_count * restarts, M), dtype=np.float32)
    for sample in range(sample_count):
        for restart in range(restarts):
            rng = np.random.default_rng(int(seed) + 1000 * int(sample) + int(restart))
            p0 = rng.uniform(0.05, 0.95, size=M).astype(np.float32)
            p0 = np.clip(p0, 1e-4, 1.0 - 1e-4)
            raw[sample * restarts + restart] = np.log(p0 / (1.0 - p0)).astype(np.float32)
    return raw


def optimize_ddnn(
    *,
    model: Any,
    ddnn: Any,
    cases: Dict[str, Any],
    device: Any,
    restarts: int,
    epochs: int,
    learning_rate: float,
    min_learning_rate: float,
    point_chunk: int,
    early_stop_min_epochs: int,
    early_stop_patience: int,
    early_stop_fraction: float,
    rel_delta: float,
    abs_delta: float,
    log_every: int,
    resume_every: int,
    resume_path: Path,
    seed: int,
    force: bool,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, int, float]:
    torch_module = ddnn.torch
    true_amplitudes = cases["amplitudes"]
    sample_count, M = true_amplitudes.shape
    trajectory_count = sample_count * int(restarts)
    sample_ids = np.repeat(np.arange(sample_count, dtype=np.int64), int(restarts))
    tau = np.asarray(cases["tau_inverse"], dtype=np.float32)
    target = torch_module.from_numpy(
        np.asarray(cases["target_terminal_inverse"][sample_ids], dtype=np.float32)
    ).to(device)
    raw_np = pinn_compatible_initial_raw(sample_count, int(restarts), M, int(seed))
    raw = torch_module.tensor(raw_np, dtype=torch_module.float32, device=device, requires_grad=True)
    optimizer = torch_module.optim.AdamW([raw], lr=float(learning_rate), weight_decay=0.0)
    scheduler = torch_module.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=max(1, int(epochs)), eta_min=float(min_learning_rate)
    )
    best_loss = torch_module.full((trajectory_count,), float("inf"), device=device)
    best_raw = raw.detach().clone()
    best_epoch = torch_module.zeros((trajectory_count,), dtype=torch_module.long, device=device)
    stale = torch_module.zeros((trajectory_count,), dtype=torch_module.long, device=device)
    start_epoch = 1
    elapsed_before = 0.0
    actual_resume = None if force else newest_resume_path(resume_path)
    if actual_resume is not None:
        payload = torch_module.load(str(actual_resume), map_location=device)
        if payload.get("case_digest") != cases["case_digest"]:
            raise RuntimeError("DDNN inverse resume belongs to different random cases.")
        if int(payload.get("restarts", -1)) != int(restarts):
            raise RuntimeError("DDNN inverse resume restart count does not match.")
        raw.data.copy_(payload["raw"].to(device))
        optimizer.load_state_dict(payload["optimizer_state"])
        scheduler.load_state_dict(payload["scheduler_state"])
        best_loss = payload["best_loss"].to(device)
        best_raw = payload["best_raw"].to(device)
        best_epoch = payload.get("best_epoch", best_epoch.cpu()).to(device)
        stale = payload["stale"].to(device)
        start_epoch = int(payload["epoch"]) + 1
        elapsed_before = float(payload.get("elapsed_sec", 0.0))
        print("[DDNN random inverse] resume from epoch %d/%d" % (start_epoch, epochs), flush=True)

    for parameter in model.parameters():
        parameter.requires_grad_(False)
    model.eval()
    stopped_epoch = int(epochs)
    plateau_fraction = 0.0
    start_time = time.perf_counter()
    print(
        "[DDNN random inverse] samples=%d restarts=%d trajectories=%d terminal_points=%d"
        % (sample_count, restarts, trajectory_count, len(tau)), flush=True
    )
    for epoch in range(start_epoch, int(epochs) + 1):
        optimizer.zero_grad(set_to_none=True)
        amplitudes = ddnn.raw_to_amplitudes(raw)
        prediction = ddnn.predict_terminal_waveforms(
            model=model,
            combinations=amplitudes,
            tau=tau,
            z_final=float(cases["z_final"]),
            device=device,
            chunk_size=int(point_chunk),
            amp_enabled=False,
            require_grad=True,
        )
        loss_vector = ddnn.relative_complex_squared_vector(
            prediction.float(), target.float()
        )
        loss = torch_module.mean(loss_vector)
        if not torch_module.isfinite(loss):
            raise FloatingPointError("Non-finite DDNN random inverse loss.")
        loss.backward()
        torch_module.nn.utils.clip_grad_norm_([raw], 10.0)
        optimizer.step()
        scheduler.step()
        with torch_module.no_grad():
            threshold = torch_module.maximum(
                torch_module.full_like(best_loss, float(abs_delta)),
                float(rel_delta) * torch_module.abs(best_loss),
            )
            improved = torch_module.isinf(best_loss) | (loss_vector < best_loss - threshold)
            best_loss = torch_module.where(improved, loss_vector, best_loss)
            best_raw = torch_module.where(improved[:, None], raw.detach(), best_raw)
            best_epoch = torch_module.where(
                improved,
                torch_module.full_like(best_epoch, int(epoch)),
                best_epoch,
            )
            stale = torch_module.where(improved, torch_module.zeros_like(stale), stale + 1)
            plateau_fraction = float(
                torch_module.mean((stale >= int(early_stop_patience)).float()).cpu()
            )
        if epoch == 1 or epoch % int(log_every) == 0 or epoch == int(epochs):
            print(
                "[DDNN random inverse] epoch=%d/%d mean=%.4e best=%.4e plateau=%.1f%%"
                % (
                    epoch, epochs, float(loss.detach().cpu()),
                    float(torch_module.mean(best_loss).detach().cpu()),
                    100.0 * plateau_fraction,
                ), flush=True,
            )
        elapsed = elapsed_before + (time.perf_counter() - start_time)
        if epoch % max(1, int(resume_every)) == 0 or epoch == int(epochs):
            atomic_torch_save(torch_module, {
                "script_version": SCRIPT_VERSION,
                "case_digest": cases["case_digest"],
                "restarts": int(restarts),
                "epoch": int(epoch),
                "raw": raw.detach().cpu(),
                "optimizer_state": optimizer.state_dict(),
                "scheduler_state": scheduler.state_dict(),
                "best_loss": best_loss.detach().cpu(),
                "best_raw": best_raw.detach().cpu(),
                "best_epoch": best_epoch.detach().cpu(),
                "stale": stale.detach().cpu(),
                "elapsed_sec": float(elapsed),
            }, resume_path)
        if epoch >= int(early_stop_min_epochs) and plateau_fraction >= float(early_stop_fraction):
            stopped_epoch = int(epoch)
            print("[DDNN random inverse] early stop at epoch %d" % epoch, flush=True)
            break

    elapsed_total = elapsed_before + (time.perf_counter() - start_time)
    with torch_module.no_grad():
        all_amplitudes = ddnn.raw_to_amplitudes(best_raw).detach().cpu().numpy()
        all_losses = best_loss.detach().cpu().numpy()
        all_best_epochs = best_epoch.detach().cpu().numpy()
    predicted = np.empty((sample_count, M), dtype=np.float32)
    selected_loss = np.empty(sample_count, dtype=np.float64)
    selected_restart = np.empty(sample_count, dtype=np.int64)
    selected_epoch = np.empty(sample_count, dtype=np.int64)
    for sample in range(sample_count):
        positions = np.arange(sample * int(restarts), (sample + 1) * int(restarts), dtype=np.int64)
        best_position = int(positions[np.argmin(all_losses[positions])])
        predicted[sample] = all_amplitudes[best_position]
        selected_loss[sample] = float(all_losses[best_position])
        selected_restart[sample] = int(best_position - sample * int(restarts))
        selected_epoch[sample] = int(all_best_epochs[best_position])
    return predicted, selected_loss, selected_restart, selected_epoch, stopped_epoch, float(elapsed_total)


def predict_ddnn_field(
    *,
    model: Any,
    ddnn: Any,
    amplitudes: np.ndarray,
    tau: np.ndarray,
    z_final: float,
    device: Any,
    point_chunk: int,
) -> np.ndarray:
    torch_module = ddnn.torch
    outputs: List[np.ndarray] = []
    batch_size = max(1, min(16, len(amplitudes)))
    for start, end in iter_batches(len(amplitudes), batch_size):
        combo = torch_module.from_numpy(np.asarray(amplitudes[start:end], dtype=np.float32)).to(device)
        with torch_module.no_grad():
            pred = ddnn.predict_terminal_waveforms(
                model=model,
                combinations=combo,
                tau=np.asarray(tau, dtype=np.float32),
                z_final=float(z_final),
                device=device,
                chunk_size=int(point_chunk),
                amp_enabled=False,
                require_grad=False,
            )
        outputs.append(pred.float().cpu().numpy())
    return np.concatenate(outputs, axis=0)


def run_ddnn_inverse(
    *,
    run_dir: Path,
    cases: Dict[str, Any],
    base_output_folder: str,
    model_seed: int,
    ddnn: Any,
    device: Any,
    restarts: int,
    epochs: int,
    learning_rate: float,
    min_learning_rate: float,
    point_chunk: int,
    early_stop_min_epochs: int,
    early_stop_patience: int,
    early_stop_fraction: float,
    rel_delta: float,
    abs_delta: float,
    log_every: int,
    resume_every: int,
    ssfm_batch_size: int,
    optimizer_seed: int,
    force: bool,
) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    output_root = (
        run_dir / base_output_folder / "ddnn_same_architecture" /
        "inverse" / ("seed_%d" % int(model_seed))
    )
    result_path = output_root / "inverse_results.csv"
    summary_path = output_root / "summary.json"
    resume_path = output_root / "inverse_resume.pt"
    if result_path.exists() and summary_path.exists() and not force:
        existing = read_json(summary_path)
        if existing.get("experiment_type") == "random_continuous_uniform_0_1":
            print("[DDNN random inverse] exists, skip:", result_path, flush=True)
            return pd.read_csv(result_path).to_dict("records"), existing
        raise RuntimeError(
            "The previous DDNN inverse folder still contains a different experiment. "
            "Run the cleanup script before the new continuous-random inverse."
        )
    if force and output_root.exists():
        shutil.rmtree(output_root)
    output_root.mkdir(parents=True, exist_ok=True)
    checkpoint = (
        run_dir / base_output_folder / "ddnn_same_architecture" /
        "train" / ("seed_%d" % int(model_seed)) / "final" / "final_ddnn.pt"
    )
    if not checkpoint.exists():
        raise FileNotFoundError("Missing DDNN forward checkpoint: %s" % checkpoint)
    model, _ = ddnn.load_checkpoint(checkpoint, device)
    predicted, objective, restart_ids, best_epochs, stopped_epoch, elapsed = optimize_ddnn(
        model=model,
        ddnn=ddnn,
        cases=cases,
        device=device,
        restarts=int(restarts),
        epochs=int(epochs),
        learning_rate=float(learning_rate),
        min_learning_rate=float(min_learning_rate),
        point_chunk=int(point_chunk),
        early_stop_min_epochs=int(early_stop_min_epochs),
        early_stop_patience=int(early_stop_patience),
        early_stop_fraction=float(early_stop_fraction),
        rel_delta=float(rel_delta),
        abs_delta=float(abs_delta),
        log_every=int(log_every),
        resume_every=int(resume_every),
        resume_path=resume_path,
        seed=int(optimizer_seed),
        force=bool(force),
    )
    predicted_initial = ddnn.make_initial_waveforms_numpy(predicted, cases["tau_full"])
    model_terminal_inverse = predict_ddnn_field(
        model=model, ddnn=ddnn, amplitudes=predicted,
        tau=cases["tau_inverse"], z_final=cases["z_final"],
        device=device, point_chunk=point_chunk,
    )
    model_terminal_full = predict_ddnn_field(
        model=model, ddnn=ddnn, amplitudes=predicted,
        tau=cases["tau_full"], z_final=cases["z_final"],
        device=device, point_chunk=point_chunk,
    )
    back_full, back_tau = run_ssfm_for_amplitudes(
        run_dir, predicted, ddnn, device, ssfm_batch_size
    )
    if not np.allclose(back_tau, cases["tau_full"], atol=1e-7, rtol=0.0):
        raise RuntimeError("DDNN SSFM backcheck grid changed unexpectedly.")
    back_inverse = interpolate_complex_batch(back_tau, back_full, cases["tau_inverse"])
    rows = common_rows(
        M=int(cases["amplitudes"].shape[1]),
        method="ddnn_frozen_forward_4restart",
        true_amplitudes=cases["amplitudes"],
        predicted_amplitudes=predicted,
        true_initial_full=cases["true_initial_full"],
        predicted_initial_full=predicted_initial,
        target_terminal_inverse=cases["target_terminal_inverse"],
        ssfm_terminal_inverse=back_inverse,
        target_terminal_full=cases["target_terminal_full"],
        ssfm_terminal_full=back_full,
        inverse_elapsed_sec=elapsed,
        selected_restart=restart_ids,
        selected_best_epoch=best_epochs,
        selected_objective=objective,
        model_terminal_inverse=model_terminal_inverse,
        model_terminal_full=model_terminal_full,
    )
    pd.DataFrame(rows).to_csv(result_path, index=False, encoding="utf-8-sig")
    summary = summarize_rows(rows, checkpoint, {
        "experiment_type": "random_continuous_uniform_0_1",
        "case_digest_sha256": cases["case_digest"],
        "shared_pinn_dataset": str(cases["root"]),
        "restarts_per_sample": int(restarts),
        "restart_count": int(restarts),
        "inverse_logic": "freeze forward DDNN; optimize 10x4 trajectories simultaneously; select each historical best restart",
        "terminal_observable": "complex",
        "inverse_input_points": int(len(cases["tau_inverse"])),
        "epochs_cap": int(epochs),
        "stopped_epoch": int(stopped_epoch),
        "inverse_core_elapsed_sec": float(elapsed),
        "optimization_elapsed_sec": float(elapsed),
        "inverse_runtime_sec_for_method_comparison": float(elapsed),
        "inverse_runtime_sec_per_sample": float(elapsed / max(1, len(rows))),
        "same_random_amplitudes_as_pinn": True,
        "same_restart_initialization_rule_as_pinn": True,
    })
    write_json(summary_path, summary)
    if resume_path.exists():
        try:
            resume_path.unlink()
        except OSError:
            pass
    print("[DDNN random inverse] saved:", result_path, flush=True)
    del model
    gc.collect()
    if device.type == "cuda":
        ddnn.torch.cuda.empty_cache()
    return rows, summary


def update_global_outputs(
    global_root: Path,
    all_rows: List[Dict[str, Any]],
    all_summaries: List[Dict[str, Any]],
) -> None:
    global_root.mkdir(parents=True, exist_ok=True)
    if all_rows:
        pd.DataFrame(all_rows).sort_values(["M", "method", "sample_rank"]).to_csv(
            global_root / "all_case_results.csv", index=False, encoding="utf-8-sig"
        )
    if all_summaries:
        pd.DataFrame(all_summaries).sort_values(["M", "method"]).to_csv(
            global_root / "comparison_summary.csv", index=False, encoding="utf-8-sig"
        )
        write_json(global_root / "comparison_summary.json", {
            "script_version": SCRIPT_VERSION,
            "rows": all_summaries,
            "primary_continuous_accuracy": "all amplitude components within absolute error 0.05",
            "case_rule": "exact PINN sample_seed=2027 amplitude arrays and 512-point terminal observations",
        })


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="PINN-compatible random continuous inverse evaluation for trained inverse CNN and frozen-forward DDNN."
    )
    parser.add_argument("--project-root", required=True)
    parser.add_argument("--runs-root", required=True)
    parser.add_argument("--M", nargs="+", type=int, required=True)
    parser.add_argument("--methods", nargs="+", choices=("cnn", "ddnn"), required=True)
    parser.add_argument("--device", default="cuda")
    parser.add_argument("--model-seed", type=int, default=2026)
    parser.add_argument("--optimizer-seed", type=int, default=42)
    parser.add_argument("--sample-seed", type=int, default=2027)
    parser.add_argument("--n-samples", type=int, default=10)
    parser.add_argument("--inverse-input-points", type=int, default=512)
    parser.add_argument("--base-output-folder", default="endpoint_all_seen_resume_v7")
    parser.add_argument("--source-cnn-folder", default="cnn_full_propagation_v2")
    parser.add_argument(
        "--v10b-script",
        default="run_fixedM_endpoint_CNN_samearch_DDNN_full_sampling_resume_v10b_windowsfix.py",
    )
    parser.add_argument("--ddnn-restarts", type=int, default=4)
    parser.add_argument("--ddnn-epochs", type=int, default=3000)
    parser.add_argument("--ddnn-learning-rate", type=float, default=3e-2)
    parser.add_argument("--ddnn-min-learning-rate", type=float, default=5e-4)
    parser.add_argument("--point-chunk", type=int, default=65536)
    parser.add_argument("--early-stop-min-epochs", type=int, default=1000)
    parser.add_argument("--early-stop-patience", type=int, default=300)
    parser.add_argument("--early-stop-fraction", type=float, default=0.90)
    parser.add_argument("--early-stop-rel-delta", type=float, default=1e-4)
    parser.add_argument("--early-stop-abs-delta", type=float, default=1e-8)
    parser.add_argument("--log-every", type=int, default=100)
    parser.add_argument("--resume-every", type=int, default=100)
    parser.add_argument("--ssfm-batch-size", type=int, default=8)
    parser.add_argument("--amp", action="store_true")
    parser.add_argument("--force-full-cache", action="store_true")
    parser.add_argument("--force", action="store_true")
    parser.add_argument(
        "--global-output-folder",
        default="PINN_CNN_DDNN_final_summary_inputs/random_continuous_inverse_v2",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    if int(args.n_samples) != 10:
        raise ValueError("Formal comparison is fixed to 10 random target waveforms.")
    if int(args.ddnn_restarts) != 4:
        raise ValueError("Formal DDNN comparison is fixed to 4 restarts per target, matching PINN.")
    project_root = Path(args.project_root).expanduser().resolve()
    runs_root = Path(args.runs_root).expanduser().resolve()
    unified, cnn, ddnn = load_v10b_runtime(project_root, str(args.v10b_script))
    device = cnn.safe_device(str(args.device))
    set_seed(int(args.optimizer_seed), cnn.torch)
    methods = tuple(dict.fromkeys(str(item).lower() for item in args.methods))
    global_root = runs_root / str(args.global_output_folder)
    all_rows: List[Dict[str, Any]] = []
    all_summaries: List[Dict[str, Any]] = []
    print("=" * 100)
    print("SCRIPT:", SCRIPT_VERSION)
    print("METHODS:", methods)
    print("PINN-COMPATIBLE CASES: sample_seed=%d, n=10, inverse grid=%d" % (
        int(args.sample_seed), int(args.inverse_input_points)
    ))
    print("DDNN: 4 restarts per target, 40 trajectories simultaneously")
    print("CNN: one deterministic direct prediction; restart is not applicable")
    print("=" * 100)

    for M in sorted(set(int(value) for value in args.M)):
        run_dir = unified._find_run_dir_highest_ratio(runs_root, int(M))
        print("\n" + "=" * 100)
        print("RANDOM CONTINUOUS INVERSE | M=%d | %s" % (M, run_dir.name))
        print("=" * 100)
        cases = generate_or_load_shared_cases(
            run_dir=run_dir,
            M=M,
            n_samples=int(args.n_samples),
            sample_seed=int(args.sample_seed),
            inverse_input_points=int(args.inverse_input_points),
            ddnn=ddnn,
            device=device,
            ssfm_batch_size=int(args.ssfm_batch_size),
            force_full_cache=bool(args.force_full_cache),
        )
        if "cnn" in methods:
            rows, summary = run_cnn_inverse(
                run_dir=run_dir,
                cases=cases,
                base_output_folder=str(args.base_output_folder),
                source_cnn_folder=str(args.source_cnn_folder),
                model_seed=int(args.model_seed),
                sample_seed=int(args.sample_seed),
                cnn=cnn,
                ddnn=ddnn,
                device=device,
                amp_enabled=bool(args.amp and device.type == "cuda"),
                ssfm_batch_size=int(args.ssfm_batch_size),
                force=bool(args.force),
            )
            all_rows.extend(rows)
            all_summaries.append(summary)
        if "ddnn" in methods:
            rows, summary = run_ddnn_inverse(
                run_dir=run_dir,
                cases=cases,
                base_output_folder=str(args.base_output_folder),
                model_seed=int(args.model_seed),
                ddnn=ddnn,
                device=device,
                restarts=int(args.ddnn_restarts),
                epochs=int(args.ddnn_epochs),
                learning_rate=float(args.ddnn_learning_rate),
                min_learning_rate=float(args.ddnn_min_learning_rate),
                point_chunk=int(args.point_chunk),
                early_stop_min_epochs=int(args.early_stop_min_epochs),
                early_stop_patience=int(args.early_stop_patience),
                early_stop_fraction=float(args.early_stop_fraction),
                rel_delta=float(args.early_stop_rel_delta),
                abs_delta=float(args.early_stop_abs_delta),
                log_every=int(args.log_every),
                resume_every=int(args.resume_every),
                ssfm_batch_size=int(args.ssfm_batch_size),
                optimizer_seed=int(args.optimizer_seed),
                force=bool(args.force),
            )
            all_rows.extend(rows)
            all_summaries.append(summary)
        update_global_outputs(global_root, all_rows, all_summaries)

    update_global_outputs(global_root, all_rows, all_summaries)
    print("\n[done] global inverse comparison inputs:", global_root, flush=True)


if __name__ == "__main__":
    main()
