# -*- coding: utf-8 -*-
"""Frozen-forward continuous-amplitude inversion, vectorized version.

Method 1
--------
The target terminal waveforms are generated by SSFM from true PAM4 amplitudes
{0.25, 0.5, 0.75, 1.0}.  During inversion the optimizer is deliberately NOT
told that four discrete levels exist: the frozen forward PINN only receives M
continuous trainable amplitudes constrained to [0,1].  Nearest-PAM4 rounding is
performed after optimization only for reporting exact-match accuracy.

Speed changes in this version
-----------------------------
* The four restarts of one sample are optimized in one tensor batch.
* With ``--batch-mode all_samples`` (or default ``auto``), all 10 samples x 4
  restarts are optimized together, i.e. one batch of 40 amplitude vectors.
* The 3000 epochs are now a maximum budget.  By default the run stops when 90%
  of restart trajectories have plateaued for the requested patience period.
* Every restart still keeps an independent best state and best epoch.
"""
from __future__ import annotations

import argparse
import json
import math
import time
from pathlib import Path
from typing import Any

import numpy as np
import torch

from train_multi_pulse_pinn import load_forward_checkpoint
from train_inverse_multi_pulse_pinn_pure_physics import (
    safe_device,
    set_seed,
    ensure_dir,
    write_json,
    write_csv_dicts,
    select_best_forward,
    infer_m_from_sources,
    preselect_unseen_samples,
    get_or_build_inverse_dataset,
    attach_dataset_row_indices,
    terminal_observable_mode,
    combo_to_text,
)
from inverse_batched_utils import run_batched_adamw, terminal_loss_vector


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Freeze forward model and optimize continuous amplitudes with terminal-only loss.")
    p.add_argument("--run-dir", required=True)
    p.add_argument("-M", "--n-pulses", type=int, default=0)
    p.add_argument("--device", default="cuda")
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--out-dir", default="")
    p.add_argument("--forward-model-path", default="")
    p.add_argument("--forward-metrics-csv", default="")
    p.add_argument("--unseen-csv", default="")
    p.add_argument("--sample-indices", default="")
    p.add_argument("--n-samples", type=int, default=10)
    p.add_argument("--sample-seed", type=int, default=2026)

    p.add_argument("--terminal-observable", default="complex", choices=["power", "complex", "power_and_complex"])
    p.add_argument("--inverse-dataset-mode", default="selected", choices=["selected", "full"])
    p.add_argument("--inverse-dataset-dir", default="")
    p.add_argument("--rebuild-inverse-dataset", action="store_true")
    p.add_argument("--inverse-dataset-dtype", default="float32", choices=["float32", "float16"])
    p.add_argument("--inverse-input-points", type=int, default=512)
    p.add_argument("--inverse-dataset-log-every", type=int, default=1)
    p.add_argument("--verbose-ssfm", action="store_true")
    p.add_argument("--t-window-t0", type=float, default=0.0)
    p.add_argument("--n-t", type=int, default=0)
    p.add_argument("--n-z", type=int, default=0)
    p.add_argument("--z-max-ld", type=float, default=0.0)
    p.add_argument("--compare-t-min", default="")
    p.add_argument("--compare-t-max", default="")
    p.add_argument("--save-terminal-field", action="store_true", default=True)
    p.add_argument("--save-initial-power", action="store_true", default=True)
    p.add_argument("--build-dataset-if-missing", action="store_true", default=True)
    p.add_argument("--inverse-max-combos", type=int, default=0)

    p.add_argument("--p-min", type=float, default=0.0)
    p.add_argument("--p-max", type=float, default=1.0)
    p.add_argument("--epochs", type=int, default=3000, help="Maximum epoch budget; automatic stopping can finish earlier.")
    p.add_argument("--restarts", type=int, default=4)
    p.add_argument("--batch-mode", choices=["auto", "all_samples", "per_sample"], default="auto")
    p.add_argument("--lr", type=float, default=3e-2)
    p.add_argument("--min-lr", type=float, default=5e-4)
    p.add_argument("--cosine-anneal", action="store_true", default=True)
    p.add_argument("--no-cosine-anneal", action="store_false", dest="cosine_anneal")
    p.add_argument("--terminal-points", type=int, default=0, help="0 means full terminal slice")
    p.add_argument("--forward-time-chunk", type=int, default=512)
    p.add_argument("--log-every", type=int, default=100)
    p.add_argument("--early-stop", action="store_true", default=True)
    p.add_argument("--no-early-stop", action="store_false", dest="early_stop")
    p.add_argument("--early-stop-min-epochs", type=int, default=1000)
    p.add_argument("--early-stop-patience", type=int, default=300)
    p.add_argument("--early-stop-fraction", type=float, default=0.90, help="Stop when this fraction of restart trajectories has plateaued.")
    p.add_argument("--early-stop-min-delta", type=float, default=1e-4, help="Relative improvement threshold (legacy argument name).")
    p.add_argument("--early-stop-abs-delta", type=float, default=1e-8)
    return p.parse_args()


def init_raw_for_uniform_p(M: int, p_min: float, p_max: float, seed: int) -> np.ndarray:
    rng = np.random.default_rng(int(seed))
    lo = float(p_min) + 0.05 * (float(p_max) - float(p_min))
    hi = float(p_max) - 0.05 * (float(p_max) - float(p_min))
    p0 = rng.uniform(lo, hi, size=M).astype(np.float32)
    y = (p0 - float(p_min)) / max(float(p_max) - float(p_min), 1e-12)
    y = np.clip(y, 1e-4, 1 - 1e-4)
    return np.log(y / (1 - y)).astype(np.float32)


def raw_to_p(raw: torch.Tensor, p_min: float, p_max: float) -> torch.Tensor:
    return float(p_min) + (float(p_max) - float(p_min)) * torch.sigmoid(raw)


def nearest_pam4_metrics(pred: np.ndarray, true: np.ndarray) -> dict[str, Any]:
    levels = np.asarray([0.25, 0.5, 0.75, 1.0], dtype=np.float32)
    rounded = levels[np.argmin(np.abs(pred[:, None] - levels[None, :]), axis=1)]
    return {
        "pred_rounded_amplitude4": [float(x) for x in rounded.tolist()],
        "amplitude4_exact_match": int(bool(np.allclose(rounded, true, atol=1e-6))),
        "amplitude4_per_pulse_accuracy": float(np.mean(np.isclose(rounded, true, atol=1e-6))),
    }


def _optimize_groups(
    *,
    args: argparse.Namespace,
    model: torch.nn.Module,
    tau: torch.Tensor,
    selected: list[dict[str, Any]],
    true_all: np.ndarray,
    Yp_t: torch.Tensor,
    Yr_t: torch.Tensor | None,
    Yi_t: torch.Tensor | None,
    zeta: float,
    observable: str,
    device: torch.device,
    mode: str,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], list[dict[str, Any]], list[dict[str, Any]]]:
    S = len(selected)
    R = int(args.restarts)
    groups = [list(range(S))] if mode == "all_samples" else [[i] for i in range(S)]
    per_sample_best: list[dict[str, Any] | None] = [None] * S
    restart_rows: list[dict[str, Any]] = []
    history_rows: list[dict[str, Any]] = []
    stop_rows: list[dict[str, Any]] = []

    for group_no, g in enumerate(groups):
        B = len(g) * R
        sample_ids = np.repeat(np.asarray(g, dtype=np.int64), R)
        restart_ids = np.tile(np.arange(R, dtype=np.int64), len(g))
        raw_np = np.empty((B, true_all.shape[1]), dtype=np.float32)
        for b, (si, ri) in enumerate(zip(sample_ids.tolist(), restart_ids.tolist())):
            raw_np[b] = init_raw_for_uniform_p(
                true_all.shape[1], args.p_min, args.p_max,
                args.seed + 1000 * int(selected[si]["rank"]) + int(ri),
            )
        initial = torch.tensor(raw_np, dtype=torch.float32, device=device)
        yp = Yp_t[g].repeat_interleave(R, dim=0)
        yr = Yr_t[g].repeat_interleave(R, dim=0) if Yr_t is not None else None
        yi = Yi_t[g].repeat_interleave(R, dim=0) if Yi_t is not None else None

        result = run_batched_adamw(
            model=model,
            tau=tau,
            y_power=yp,
            y_real=yr,
            y_imag=yi,
            initial_parameter=initial,
            decode_parameter=lambda x: raw_to_p(x, args.p_min, args.p_max),
            zeta=zeta,
            observable=observable,
            epochs=args.epochs,
            lr=args.lr,
            min_lr=args.min_lr,
            cosine_anneal=args.cosine_anneal,
            terminal_points=args.terminal_points,
            forward_time_chunk=args.forward_time_chunk,
            log_every=args.log_every,
            early_stop=args.early_stop,
            early_stop_min_epochs=args.early_stop_min_epochs,
            early_stop_patience=args.early_stop_patience,
            early_stop_fraction=args.early_stop_fraction,
            early_stop_rel_delta=args.early_stop_min_delta,
            early_stop_abs_delta=args.early_stop_abs_delta,
            sample_ids=sample_ids,
            restart_ids=restart_ids,
            mode="idea1a_continuous_batched",
            history_extra=lambda p: [{"P": combo_to_text(row)} for row in p],
        )
        history_rows.extend(result.history)
        stop_rows.append({
            "group": group_no,
            "sample_indices": [int(x) for x in g],
            "batch_size": B,
            "stopped_epoch": int(result.stopped_epoch),
            "plateau_fraction": float(result.plateau_fraction),
        })

        with torch.no_grad():
            pbest = raw_to_p(result.best_parameter.to(device), args.p_min, args.p_max)
            loss_v, power_v, complex_v = terminal_loss_vector(
                model, tau, pbest, yp, yr, yi, zeta, observable, 0, args.forward_time_chunk
            )
        p_np = pbest.detach().cpu().numpy()
        lv = loss_v.detach().cpu().numpy()
        pv = power_v.detach().cpu().numpy()
        cv = complex_v.detach().cpu().numpy() if complex_v is not None else None
        best_ep = result.best_epoch.detach().cpu().numpy()

        for b, (si, ri) in enumerate(zip(sample_ids.tolist(), restart_ids.tolist())):
            true = true_all[si]
            pred = p_np[b]
            cand = {
                "sample_rank": int(si),
                "dataset_index": int(selected[si]["dataset_index"]),
                "restart": int(ri),
                "best_epoch": int(best_ep[b]),
                "terminal_loss": float(lv[b]),
                "terminal_power_loss": float(pv[b]),
                "terminal_complex_loss": "" if cv is None else float(cv[b]),
                "true_amplitudes": combo_to_text(true),
                "pred_amplitudes": [float(x) for x in pred.tolist()],
                "p_mae": float(np.mean(np.abs(pred - true))),
                "p_rmse": float(np.sqrt(np.mean((pred - true) ** 2))),
                **nearest_pam4_metrics(pred, true),
            }
            restart_rows.append(cand)
            old = per_sample_best[si]
            if old is None or cand["terminal_loss"] < old["terminal_loss"]:
                per_sample_best[si] = cand

    return [x for x in per_sample_best if x is not None], restart_rows, history_rows, stop_rows


def main() -> None:
    wall_clock_t0 = time.time()
    args = parse_args()
    set_seed(args.seed)
    device = safe_device(args.device)
    run_dir = Path(args.run_dir)
    out_dir = ensure_dir(args.out_dir or (run_dir / "inverse" / f"01_continuous_0to1_amplitude4_N{args.n_samples}_seed{args.sample_seed}"))

    forward_ckpt, forward_label, forward_info = select_best_forward(args)
    M = infer_m_from_sources(args, run_dir, forward_ckpt)
    args.n_pulses = int(M)
    selected = preselect_unseen_samples(args, run_dir, M, out_dir)
    args.selected_dataset_indices = ",".join(str(int(s["dataset_index"])) for s in selected)
    args.selected_indices_source = "idea1a_continuous_preselection"
    ds_root, ds_meta = get_or_build_inverse_dataset(args, run_dir, M, forward_ckpt, device)
    selected = attach_dataset_row_indices(selected, ds_root, out_dir)

    model = load_forward_checkpoint(forward_ckpt, device).to(device)
    model.eval()
    for p in model.parameters():
        p.requires_grad_(False)

    tau = torch.tensor(np.load(ds_root / "tau_input.npy"), dtype=torch.float32, device=device)
    Yp = np.load(ds_root / "Y_terminal_power.npy", mmap_mode="r")
    Yr = np.load(ds_root / "Y_terminal_real.npy", mmap_mode="r") if (ds_root / "Y_terminal_real.npy").exists() else None
    Yi = np.load(ds_root / "Y_terminal_imag.npy", mmap_mode="r") if (ds_root / "Y_terminal_imag.npy").exists() else None
    rows = [int(s["row_index"]) for s in selected]
    Yp_t = torch.tensor(np.asarray(Yp[rows], dtype=np.float32), dtype=torch.float32, device=device)
    Yr_t = torch.tensor(np.asarray(Yr[rows], dtype=np.float32), dtype=torch.float32, device=device) if Yr is not None else None
    Yi_t = torch.tensor(np.asarray(Yi[rows], dtype=np.float32), dtype=torch.float32, device=device) if Yi is not None else None
    true_all = np.asarray([s["powers"] for s in selected], dtype=np.float32)
    pam4_levels = np.asarray([0.25, 0.5, 0.75, 1.0], dtype=np.float32)
    if not np.all(np.isclose(true_all[..., None], pam4_levels.reshape(1, 1, -1), atol=1e-7).any(axis=-1)):
        raise RuntimeError("Method 1 requires SSFM targets generated from exact PAM4 amplitudes.")
    if abs(float(args.p_min) - 0.0) > 1e-12 or abs(float(args.p_max) - 1.0) > 1e-12:
        raise RuntimeError("Method 1 must invert blindly in the continuous box [0,1]^M.")
    zeta = float(getattr(model, "z_max_ld", ds_meta.get("z_max_ld", 4.0)))
    observable = terminal_observable_mode(args)

    t_all = time.time()
    requested_mode = args.batch_mode
    actual_mode = "all_samples" if requested_mode in {"auto", "all_samples"} else "per_sample"
    try:
        best_rows, restart_rows, history_rows, stop_rows = _optimize_groups(
            args=args, model=model, tau=tau, selected=selected, true_all=true_all,
            Yp_t=Yp_t, Yr_t=Yr_t, Yi_t=Yi_t, zeta=zeta,
            observable=observable, device=device, mode=actual_mode,
        )
    except RuntimeError as exc:
        if requested_mode == "auto" and "out of memory" in str(exc).lower():
            print("[auto batch] GPU memory is insufficient for all samples; falling back to per-sample batched restarts.", flush=True)
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            actual_mode = "per_sample"
            best_rows, restart_rows, history_rows, stop_rows = _optimize_groups(
                args=args, model=model, tau=tau, selected=selected, true_all=true_all,
                Yp_t=Yp_t, Yr_t=Yr_t, Yi_t=Yi_t, zeta=zeta,
                observable=observable, device=device, mode=actual_mode,
            )
        else:
            raise

    write_csv_dicts(out_dir / "batched_history.csv", history_rows)
    write_csv_dicts(out_dir / "all_restart_summary.csv", restart_rows)
    write_csv_dicts(out_dir / "per_sample_summary.csv", best_rows)
    write_json(out_dir / "automatic_epoch_stop.json", {
        "maximum_epoch_budget": int(args.epochs),
        "actual_batch_mode": actual_mode,
        "stop_groups": stop_rows,
        "recommended_observed_stop_epoch": int(max(r["stopped_epoch"] for r in stop_rows)),
        "criterion": {
            "plateau_fraction": float(args.early_stop_fraction),
            "patience": int(args.early_stop_patience),
            "min_epochs": int(args.early_stop_min_epochs),
            "relative_delta": float(args.early_stop_min_delta),
            "absolute_delta": float(args.early_stop_abs_delta),
        },
    })

    # Preserve the old per-sample layout.
    for row in best_rows:
        si = int(row["sample_rank"])
        sdir = ensure_dir(out_dir / f"s{int(selected[si]['rank']):02d}_i{int(selected[si]['dataset_index'])}")
        write_json(sdir / "summary.json", {"method": "idea1a_continuous_terminal_only_batched", **row})
        write_csv_dicts(sdir / "history.csv", [h for h in history_rows if int(h["sample"]) == si])

    optimization_elapsed = float(time.time() - t_all)
    access = dict(ds_meta.get("_dataset_access", {}) or {})
    target_ssfm_original = float(access.get("ssfm_generation_elapsed_sec_original", ds_meta.get("build_elapsed_sec", 0.0)) or 0.0)
    target_ssfm_this_run = float(access.get("ssfm_generation_elapsed_sec_this_call", 0.0) or 0.0)
    dataset_prepare_this_run = float(access.get("prepare_elapsed_sec_this_call", 0.0) or 0.0)
    aggregate = {
        "method": "pam4_targets_blind_continuous_0to1_batched",
        "method_semantics": {
            "target_waveform_generator": "SSFM",
            "target_true_amplitude_levels": [0.25, 0.5, 0.75, 1.0],
            "inverse_search_space": "continuous [0,1]^M",
            "inverse_knows_pam4_levels": False,
            "pam4_rounding_stage": "post-optimization evaluation only",
        },
        "run_dir": str(run_dir),
        "forward_model": str(forward_ckpt),
        "forward_label": forward_label,
        "forward_selection": forward_info,
        "n_samples": len(best_rows),
        "restarts_per_sample": int(args.restarts),
        "requested_batch_mode": requested_mode,
        "actual_batch_mode": actual_mode,
        "mean_amplitude_mae": float(np.mean([r["p_mae"] for r in best_rows])),
        "mean_amplitude_rmse": float(np.mean([r["p_rmse"] for r in best_rows])),
        "terminal_loss_mean": float(np.mean([r["terminal_loss"] for r in best_rows])),
        "terminal_rel_l2_mean": float(np.mean([np.sqrt(max(0.0, float(r["terminal_loss"]))) for r in best_rows])),
        "terminal_power_rel_l2_mean": float(np.mean([np.sqrt(max(0.0, float(r["terminal_power_loss"]))) for r in best_rows])),
        "terminal_complex_rel_l2_mean": (
            float(np.mean([np.sqrt(max(0.0, float(r["terminal_complex_loss"]))) for r in best_rows if r["terminal_complex_loss"] != ""]))
            if any(r["terminal_complex_loss"] != "" for r in best_rows) else None
        ),
        "amplitude4_exact_match_count_after_rounding": int(sum(r["amplitude4_exact_match"] for r in best_rows)),
        "amplitude4_exact_match_accuracy_after_rounding": float(np.mean([r["amplitude4_exact_match"] for r in best_rows])),
        "amplitude4_per_pulse_accuracy_after_rounding": float(np.mean([r["amplitude4_per_pulse_accuracy"] for r in best_rows])),
        "best_epoch_p50": float(np.percentile([r["best_epoch"] for r in restart_rows], 50)),
        "best_epoch_p90": float(np.percentile([r["best_epoch"] for r in restart_rows], 90)),
        "best_epoch_max": int(max(r["best_epoch"] for r in restart_rows)),
        "target_ssfm_dataset": str(ds_root),
        "target_ssfm_dataset_reused_this_run": bool(access.get("reused_this_call", False)),
        "target_ssfm_generation_sec_original": target_ssfm_original,
        "target_ssfm_generation_sec_this_run": target_ssfm_this_run,
        "dataset_prepare_sec_this_run": dataset_prepare_this_run,
        "inverse_core_elapsed_sec": optimization_elapsed,
        "ssfm_reconstruction_elapsed_sec": 0.0,
        "end_to_end_sec_from_scratch": float(target_ssfm_original + optimization_elapsed),
        "wall_clock_sec_this_run": float(time.time() - wall_clock_t0),
        "elapsed_sec_total": optimization_elapsed,
        "args": vars(args),
    }
    write_json(out_dir / "summary.json", aggregate)
    print(json.dumps(aggregate, indent=2, ensure_ascii=False), flush=True)


if __name__ == "__main__":
    main()
